version: '3'
services:
  prisma_core:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - '${PRISMA_PORT:-4454}:${PRISMA_PORT:-4454}'
    environment:
      PRISMA_CONFIG: |
        # managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        secret: ${PRISMA_SECRET}
        port: ${PRISMA_PORT:-4454}
        databases:
          default:
            connector: postgres
            host: postgres_core
            port: 5432
            user: ${PG_USER}
            password: ${PG_PASSWORD}
            migrations: true
  postgres_core:
    image: postgres:10.3
    environment:
      POSTGRES_USER: ${PG_USER:-prisma}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-prisma}
    volumes:
      - postgres_core:/var/lib/postgresql-prisma/data
volumes:
  postgres_core: ~
